### ISSUE TITLE
create project failed

### ISSUE THREAD

**Issue by ghost** [qiciengine/qiciengine#14]
tested with qiciengine-1.1.3.

```
-----> LIST_DIR
-----> LIST_DIR
-----> LIST_DIR
-----> LIST_DIR
-----> LIST_DIR
-----> CREATE_PROJECT
cmd：CREATE_PROJECT，exception：[TypeError: Object #<Object> has no method 'isAbsolute']
TypeError: Object #<Object> has no method 'isAbsolute'
    at Object.createProject (/Users/jryin/workspace/qiciengine/releases/editorservice/daemons/Project.js:112:15)
    at Object.COMMAND_D.registerCmd.main (/Users/jryin/workspace/qiciengine/releases/editorservice/cmd/CREATE_PROJECT.js:10:29)
    at dispatch (/Users/jryin/workspace/qiciengine/releases/editorservice/daemons/socket/Command.js:109:33)
    at Socket.<anonymous> (/Users/jryin/workspace/qiciengine/releases/editorservice/daemons/socket/Command.js:28:9)
    at Socket.emit (events.js:98:17)
    at Socket.onevent (/Users/jryin/workspace/qiciengine/releases/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/Users/jryin/workspace/qiciengine/releases/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/Users/jryin/workspace/qiciengine/releases/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/jryin/workspace/qiciengine/releases/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/Users/jryin/workspace/qiciengine/releases/node_modules/socket.io-parser/index.js:247:12)
```

**Comment by ghost** [comment]
Works after upgrade Node to v4.4.7.
