### ISSUE TITLE
Not work for node 8.1.3

### ISSUE THREAD

**Issue by MarStarck** [qiciengine/qiciengine#21]
`Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:40:20
    at Object.<anonymous> (D:\Projects\QICI_Engine_1.1.4\node_modules\fs-extra\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)    at tryModuleLoad (module.js:466:12)`

**Comment by Morabaraba** [comment]
Only seem to work up to [nodejs v4](http://ask.qiciengine.com/?/question/82). Use nvm or [download v4 for your os](https://nodejs.org/dist/latest-v4.x/).
